name: Lint Code Base

#
# Documentation:
# https://github.com/github/super-linter
#

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  call:
    uses: yuya-hanzawa/base_repo/.github/workflows/called_workflows.yml@main
    secrets: inherit
